---
# 
# project meta-data used for various project tasks like building gem packages
# 
name: antlr3

version: "1.2.1"
antlr_version: "3.2.1"

summary: |-
  Fully-featured ruby parser generation for ANTLR version 3.
author: Kyle Yetter
email: kcy5b@yahoo.com

has_rdoc: true
rubyforge_project: antlr3
executables: antlr4ruby

development_dependencies: [rspec]
requirements: [java]
required_ruby_version: ">= 1.8.7"

# 
# important paths in the project tree
# 
antlr:
  jar: antlr-full-$(antlr_version).jar
  templates: org/antlr/codegen/templates
  targets: org/antlr/codegen
  
bundler: !pathmap
  lib: vendor/bundler/lib
  environment: vendor/environment.rb
  config: config/gemfile
  top: vendor/bundler
  gems: vendor/gems
  
rake_tasks: !path dev-lib/tasks
dev_lib: !path dev-lib
lib: !path lib
java: !path java
functional_testing: !path test/functional

#
# project file lists for various purposes
# 
lib_jars:
  - antlr-2.7.7.jar
  - antlr-runtime-$(antlr_version).jar
  - stringtemplate-$(antlr_version).jar

unit_tests: !pathlist
  - test/unit/*.rb

functional_tests: !pathlist
  - test/functional/*/*.rb

package_files: !pathlist
  include:
    - lib/**/*.rb
    - test/unit/**/*
    - test/functional/*/*.rb
    - templates/*.stg
    - samples/Cpp.g
    - samples/ANTLRv3Grammar.g
    - *.txt
    - java/antlr-full-$(antlr_version).jar
    - java/*.java
  exclude:
    - lib/antlr3/token/*.rb


#   
# project environment setup
# 
load:
  - dev-lib/core-ext/**/*.rb

load_path:
  - lib
  - dev-lib

# these are required after the gem-neutral environment is established
# via $project.load_environment
environment_require:
  - pp
  - facets/string/tab
  - facets/string/snakecase
  - facets/string/camelcase
  - facets/module/module_load
  - facets/module/modspace
  - facets/class_extend
  - facets/array/pad
  - facets/comparable/bound
  - facets/progressbar
  - ansi-color
