---
# 
# project meta-data used for various project tasks like building gem packages
# 
name: antlr3

version: "1.4.0"
antlr_version: "3.2.1"

summary: |-
  Fully-featured ruby parser generation for ANTLR version 3.
author: Kyle Yetter
email: kcy5b@yahoo.com
homepage: http://github.com/ohboyohboyohboy/antlr3

has_rdoc: true
rubyforge_project: antlr3
executables: antlr4ruby

development_dependencies: [rspec]
requirements: [java]
required_ruby_version: ">= 1.8.7"

doc: !group
  rdoc: !path doc/rdoc
  ri:   !path doc/ri
  options:
    - "-Nd"
  files: !pathlist
    include:
      - lib/**/*.rb
    exclude:
      - lib/antlr3/token/*.rb

package: !group
  base: !path pkg
  dir:  !path pkg/$(name)-$(version)
  files: !pathlist
    include:
      - bin/antlr4ruby
      - lib/**/*.rb
      - test/unit/**/*
      - test/functional/*/*.rb
      - templates/*.stg
      - samples/CPP.g
      - samples/ANTLRv3Grammar.g
      - *.txt
      - java/antlr-full-$(antlr_version).jar
      - java/*.java
    exclude:
      - DEVELOPER-README.txt
      - lib/antlr3/token/*.rb
  
# 
# important paths in the project tree
# 
antlr: !pathmap
  jar: java/antlr-full-$(antlr_version).jar
  templates: java/org/antlr/codegen/templates/Ruby
  targets: java/org/antlr/codegen
  target: java/RubyTarget.java

bundler: !pathmap
  top: vendor/bundler
  lib: vendor/bundler/lib
  plugin: vendor/bundler/lib/rubygems_plugin.rb
  environment: vendor/environment.rb
  config: config/gemfile
  gems: vendor/gems

test: !pathmap
  unit: test/unit
  functional: test/functional
  performance: test/performance
  log: log/test.log
  results: log
  
rake_tasks: !path dev-lib/tasks
dev_lib: !path dev-lib
lib: !path lib
java: !path java
functional_testing: !path test/functional

#
# project file lists for various purposes
# 
lib_jars:
  - antlr-2.7.7.jar
  - antlr-runtime-$(antlr_version).jar
  - stringtemplate-$(antlr_version).jar

unit_tests: !pathlist
  - test/unit/*.rb

functional_tests: !pathlist
  - test/functional/*/*.rb

templates: !pathlist
  - templates/*.stg

#   
# project environment setup
# 
load:
  - dev-lib/core-ext/**/*.rb

load_path:
  - lib
  - dev-lib

system_path:
  - scripts
  - bin
  - vendor/bin
# these are required after the gem-neutral environment is established
# via $project.load_environment
environment_require:
  - pp
  - facets/string/tab
  - facets/string/snakecase
  - facets/string/camelcase
  - facets/module/module_load
  - facets/module/modspace
  - facets/class_extend
  - facets/array/pad
  - facets/comparable/bound
  - facets/progressbar
  - ansi-color
