---
name: antlr3
author: Kyle Yetter
email: kcy5b@yahoo.com
antlr_version: "3.2"
load_path:
  - lib
  - utility
paths:
  java: java
  lib: lib
  dist: dist
  unit_test: test/unit
  dev_lib: utility
  antlr:
    base: package
    templates: package/tool/src/main/resources/org/antlr/codegen/templates
    targets: package/tool/src/main/java/org/antlr/codegen
  templates: templates
clean_globs:
  - **/*~
  - test/functional/*/*/*
  - test/functional/*/*/
autoload:
  Logger: logger
post_install_message: |-
  
