---
name: antlr3
author: Kyle Yetter
email: kcy5b@yahoo.com
url: 
in_short: # FIXME: write a one-line description of the project
description: |-
  # FIXME: write a description with more detail
created_on: 2009-04-25
version: kcy5b@yahoo.com
dependencies:
  -
readme: README.txt
manifest: Manifest.txt
