---
0:
  - passed
  - is totally functional
1:
  - failed
  - failed to generate code due to ANTLR errors
2: 
  - failed
  - generated code that has syntax errors
3:
  - failed
  - generated code that has runtime errors
4:
  - failed
  - did not pass its test script
98:
  - pending
  - generated acceptable code but does not have test code
99:
  - failed
  - produced runtime errors during its compile script
100:
  - unknown
  - has not been tested
101:
  - broken
  - test exists but has problems